require 'dotenv'
Dotenv.load
require 'open-uri'
require 'json'
require 'pp'

base_url = "https://www.googleapis.com/civicinfo/v2/representatives?address="
address = "633+Folsom+St%2CSan+Francisco%2CCA"
api_key = "&key=#{ENV['GOOGLE_CIVIC_API_KEY']}"
full_request_uri = base_url + address + api_key

#representatives_data = JSON.parse(open(full_request_uri).read)

representatives_data = {"kind"=>"civicinfo#representativeInfoResponse",
 "normalizedInput"=>
  {"line1"=>"633 folsom street",
   "city"=>"san francisco",
   "state"=>"CA",
   "zip"=>"94107"},
 "divisions"=>
  {"ocd-division/country:us/state:ca/cd:12"=>
    {"name"=>"California's 12th congressional district", "officeIndices"=>[0]},
   "ocd-division/country:us"=>
    {"name"=>"United States", "officeIndices"=>[1, 2]},
   "ocd-division/country:us/state:ca/county:san_francisco"=>
    {"name"=>"San Francisco County",
     "alsoKnownAs"=>["ocd-division/country:us/state:ca/place:san_francisco"],
     "officeIndices"=>[6, 7, 8, 9, 10, 11, 12]},
   "ocd-division/country:us/state:ca"=>
    {"name"=>"California",
     "officeIndices"=>[3, 4, 5, 13, 14, 15, 16, 17, 18]}},
 "offices"=>
  [{"name"=>"United States House of Representatives CA-12",
    "divisionId"=>"ocd-division/country:us/state:ca/cd:12",
    "levels"=>["country"],
    "roles"=>["legislatorLowerBody"],
    "officialIndices"=>[0]},
   {"name"=>"President of the United States",
    "divisionId"=>"ocd-division/country:us",
    "levels"=>["country"],
    "roles"=>["headOfState", "headOfGovernment"],
    "officialIndices"=>[1]},
   {"name"=>"Vice-President of the United States",
    "divisionId"=>"ocd-division/country:us",
    "levels"=>["country"],
    "roles"=>["deputyHeadOfGovernment"],
    "officialIndices"=>[2]},
   {"name"=>"United States Senate",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "levels"=>["country"],
    "roles"=>["legislatorUpperBody"],
    "officialIndices"=>[3, 4]},
   {"name"=>"Governor",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "levels"=>["administrativeArea1"],
    "roles"=>["headOfGovernment"],
    "officialIndices"=>[5]},
   {"name"=>"Lieutenant Governor",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "levels"=>["administrativeArea1"],
    "roles"=>["deputyHeadOfGovernment"],
    "officialIndices"=>[6]},
   {"name"=>"Mayor",
    "divisionId"=>"ocd-division/country:us/state:ca/county:san_francisco",
    "officialIndices"=>[7]},
   {"name"=>"Sheriff",
    "divisionId"=>"ocd-division/country:us/state:ca/county:san_francisco",
    "officialIndices"=>[8]},
   {"name"=>"Treasurer",
    "divisionId"=>"ocd-division/country:us/state:ca/county:san_francisco",
    "officialIndices"=>[9]},
   {"name"=>"County Clerk",
    "divisionId"=>"ocd-division/country:us/state:ca/county:san_francisco",
    "officialIndices"=>[10]},
   {"name"=>"City Attorney",
    "divisionId"=>"ocd-division/country:us/state:ca/county:san_francisco",
    "officialIndices"=>[11]},
   {"name"=>"Assessor-Recorder",
    "divisionId"=>"ocd-division/country:us/state:ca/county:san_francisco",
    "officialIndices"=>[12]},
   {"name"=>"District Attorney",
    "divisionId"=>"ocd-division/country:us/state:ca/county:san_francisco",
    "officialIndices"=>[13]},
   {"name"=>"State Treasurer",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "officialIndices"=>[14]},
   {"name"=>"Attorney General",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "officialIndices"=>[15]},
   {"name"=>"State Controller",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "officialIndices"=>[16]},
   {"name"=>"Secretary of State",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "officialIndices"=>[17]},
   {"name"=>"Insurance Commissioner",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "officialIndices"=>[18]},
   {"name"=>"State Superintendent of Public Instruction",
    "divisionId"=>"ocd-division/country:us/state:ca",
    "officialIndices"=>[19]}],
 "officials"=>
  [{"name"=>"Nancy Pelosi",
    "address"=>
     [{"line1"=>"235 cannon h.o.b.",
       "city"=>"washington",
       "state"=>"DC",
       "zip"=>"20515"}],
    "party"=>"Democratic",
    "phones"=>["(202) 225-4965"],
    "urls"=>["http://pelosi.house.gov/"],
    "photoUrl"=>"http://bioguide.congress.gov/bioguide/photo/P/P000197.jpg",
    "channels"=>
     [{"type"=>"Facebook", "id"=>"NancyPelosi"},
      {"type"=>"Twitter", "id"=>"NancyPelosi"},
      {"type"=>"YouTube", "id"=>"nancypelosi"},
      {"type"=>"GooglePlus", "id"=>"+NancyPelosi"}]},
   {"name"=>"Barack Obama",
    "address"=>
     [{"line1"=>"The White House",
       "line2"=>"1600 pennsylvania avenue nw",
       "city"=>"washington",
       "state"=>"DC",
       "zip"=>"20500"}],
    "party"=>"Democratic",
    "phones"=>["(202) 456-1111"],
    "urls"=>["http://www.whitehouse.gov/"],
    "photoUrl"=>
     "http://www.whitehouse.gov/sites/default/files/imagecache/admin_official_lowres/administration-official/ao_image/president_official_portrait_hires.jpg",
    "channels"=>
     [{"type"=>"GooglePlus", "id"=>"+whitehouse"},
      {"type"=>"Facebook", "id"=>"whitehouse"},
      {"type"=>"Twitter", "id"=>"whitehouse"},
      {"type"=>"YouTube", "id"=>"barackobama"}]},
   {"name"=>"Joseph R. Biden",
    "address"=>
     [{"line1"=>"The White House",
       "line2"=>"1600 pennsylvania avenue nw",
       "city"=>"washington",
       "state"=>"DC",
       "zip"=>"20500"}],
    "party"=>"Democratic",
    "phones"=>["(202) 456-1111"],
    "urls"=>["http://www.whitehouse.gov/"],
    "photoUrl"=>
     "http://www.whitehouse.gov/sites/default/files/imagecache/admin_official_lowres/administration-official/ao_image/vp_portrait.jpeg",
    "channels"=>
     [{"type"=>"GooglePlus", "id"=>"+whitehouse"},
      {"type"=>"Facebook", "id"=>"whitehouse"},
      {"type"=>"Twitter", "id"=>"whitehouse"}]},
   {"name"=>"Dianne Feinstein",
    "address"=>
     [{"line1"=>"331 hart senate office building",
       "city"=>"washington",
       "state"=>"DC",
       "zip"=>"20510"}],
    "party"=>"Democratic",
    "phones"=>["(202) 224-3841"],
    "urls"=>["http://www.feinstein.senate.gov/public/"],
    "photoUrl"=>
     "http://feinstein.senate.gov/public/_images/aboutdianne/officiaphoto-thumbl.jpg",
    "channels"=>
     [{"type"=>"Facebook", "id"=>"SenatorFeinstein"},
      {"type"=>"Twitter", "id"=>"SenFeinstein"},
      {"type"=>"YouTube", "id"=>"SenatorFeinstein"}]},
   {"name"=>"Barbara Boxer",
    "address"=>
     [{"line1"=>"112 hart senate office building",
       "city"=>"washington",
       "state"=>"DC",
       "zip"=>"20510"}],
    "party"=>"Democratic",
    "phones"=>["(202) 224-3553"],
    "urls"=>["http://www.boxer.senate.gov/"],
    "photoUrl"=>"http://bioguide.congress.gov/bioguide/photo/B/B000711.jpg",
    "channels"=>
     [{"type"=>"Facebook", "id"=>"senatorboxer"},
      {"type"=>"Twitter", "id"=>"SenatorBoxer"},
      {"type"=>"YouTube", "id"=>"SenatorBoxer"}]},
   {"name"=>"Edmund G. Brown Jr.",
    "address"=>
     [{"line1"=>"c/o State Capitol",
       "line2"=>"Suite 1173",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"95814"}],
    "party"=>"Democratic",
    "phones"=>["(916) 445-2841"],
    "urls"=>["http://gov.ca.gov/home.php"],
    "channels"=>
     [{"type"=>"GooglePlus", "id"=>"+JerryBrown"},
      {"type"=>"Facebook", "id"=>"jerrybrown"},
      {"type"=>"Twitter", "id"=>"JerryBrownGov"}]},
   {"name"=>"Gavin Newsom",
    "address"=>
     [{"line1"=>"State Capitol",
       "line2"=>"Suite 1114",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"95814"}],
    "party"=>"Democratic",
    "phones"=>["(916) 445-8994"],
    "urls"=>["http://www.ltg.ca.gov/"],
    "emails"=>["gavin@gavinnewsom.com"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"GavinNewsom"},
      {"type"=>"Twitter", "id"=>"gavinnewsom"}]},
   {"name"=>"Edwin M. Lee",
    "address"=>
     [{"line1"=>"City Hall",
       "line2"=>"Room 200",
       "line3"=>"1 Dr., carlton b. goodlett place",
       "city"=>"san francisco",
       "state"=>"CA",
       "zip"=>"94102"}],
    "party"=>"Nonpartisan",
    "phones"=>["(415) 554-6141"],
    "urls"=>["http://sfmayor.org/"],
    "photoUrl"=>"http://www.sfmayor.org/Modules/ShowImage.aspx?imageid=205",
    "emails"=>["mayoredwinlee@sfgov.org"],
    "channels"=>
     [{"type"=>"GooglePlus", "id"=>"111835610796626268769"},
      {"type"=>"Facebook", "id"=>"mayoredwinlee"},
      {"type"=>"Twitter", "id"=>"mayoredlee"},
      {"type"=>"YouTube", "id"=>"mayoredlee"}]},
   {"name"=>"Vicki L. Hennessy",
    "address"=>
     [{"line1"=>"1 carlton goodlett place",
       "city"=>"san francisco",
       "state"=>"CA",
       "zip"=>"94102"}],
    "party"=>"Nonpartisan",
    "phones"=>["(415) 554-7225"],
    "urls"=>["http://www6.sfgov.org/index.aspx?page=138"],
    "emails"=>["sheriff@sfgov.org"]},
   {"name"=>"Jose Cisneros",
    "address"=>
     [{"line1"=>"City Hall",
       "line2"=>"Room 140",
       "line3"=>"1 Dr., carlton b. goodlett place",
       "city"=>"san francisco",
       "state"=>"CA",
       "zip"=>"94102"}],
    "party"=>"Nonpartisan",
    "phones"=>["(415) 701-2311"],
    "urls"=>["http://www.sftreasurer.org/"]},
   {"name"=>"Karen Hong",
    "address"=>
     [{"line1"=>"City Hall",
       "line2"=>"Room 168 1 Dr.",
       "line3"=>"carlton b. goodlett place",
       "city"=>"san francisco",
       "state"=>"CA",
       "zip"=>"94102"}],
    "party"=>"Nonpartisan",
    "phones"=>["(415) 554-4950"],
    "urls"=>["http://www.sfgov.org/countyclerk"],
    "emails"=>["county.clerk@sfgov.org"]},
   {"name"=>"Dennis J. Herrera",
    "address"=>
     [{"line1"=>"City Hall",
       "line2"=>"Room 234 1 Dr.",
       "line3"=>"carlton b. goodlett place",
       "city"=>"san francisco",
       "state"=>"CA",
       "zip"=>"94102"}],
    "party"=>"Nonpartisan",
    "phones"=>["(415) 554-4700"],
    "urls"=>["http://www.sfcityattorney.org/"],
    "emails"=>["cityattorney@sfgov.org"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"sfcityattorney"},
      {"type"=>"Twitter", "id"=>"sfcityattorney"}]},
   {"name"=>"Carmen Chu",
    "address"=>
     [{"line1"=>"1155 Market Street",
       "line2"=>"Fifth Floor",
       "city"=>"san francisco",
       "state"=>"CA",
       "zip"=>"94103"}],
    "party"=>"Nonpartisan",
    "phones"=>["(415) 554-5531"],
    "urls"=>["http://www.sfassessor.org/"],
    "emails"=>["assessor@sfgov.org"]},
   {"name"=>"George Gascon",
    "address"=>
     [{"line1"=>"850 bryant street",
       "city"=>"san francisco",
       "state"=>"CA",
       "zip"=>"94103"}],
    "party"=>"Nonpartisan",
    "phones"=>["(415) 553-1751"],
    "urls"=>["http://www.sfdistrictattorney.org/"],
    "emails"=>["DistrictAttorney@sfgov.org"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"133101130104597"},
      {"type"=>"Twitter", "id"=>"SFDAOffice"}]},
   {"name"=>"John Chiang",
    "address"=>
     [{"line1"=>"P.O. Box 942809",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"94209"}],
    "party"=>"Democratic",
    "phones"=>["(916) 653-2995"],
    "urls"=>["http://www.treasurer.ca.gov/"],
    "channels"=>[{"type"=>"Twitter", "id"=>"STONewsroom"}]},
   {"name"=>"Kamala D. Harris",
    "address"=>
     [{"line1"=>"P.O. Box 944255",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"94244"}],
    "party"=>"Democratic",
    "phones"=>["(916) 445-9555"],
    "urls"=>["http://www.ag.ca.gov/"],
    "emails"=>["piu@doj.ca.gov"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"149799031764167"},
      {"type"=>"Twitter", "id"=>"CalAGHarris"}]},
   {"name"=>"Betty T. Yee",
    "address"=>
     [{"line1"=>"P.O. Box 942850",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"94250"}],
    "party"=>"Democratic",
    "phones"=>["(916) 445-2636"],
    "urls"=>["http://www.sco.ca.gov/"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"137732083043662"},
      {"type"=>"Twitter", "id"=>"CAController"}]},
   {"name"=>"Alex Padilla",
    "address"=>
     [{"line1"=>"1500 11th street",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"95814"}],
    "party"=>"Democratic",
    "phones"=>["(916) 653-7244"],
    "urls"=>["http://www.sos.ca.gov/"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"CaliforniaSOS"},
      {"type"=>"Twitter", "id"=>"CASOSvote"}]},
   {"name"=>"Dave Jones",
    "address"=>
     [{"line1"=>"300 capitol mall",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"95814"}],
    "party"=>"Democratic",
    "phones"=>["(916) 492-3500"],
    "urls"=>["http://www.insurance.ca.gov/"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"insurancecagov"},
      {"type"=>"Twitter", "id"=>"CDINews"}]},
   {"name"=>"Tom Torlakson",
    "address"=>
     [{"line1"=>"1430 N Street",
       "line2"=>"Suite 5602",
       "city"=>"sacramento",
       "state"=>"CA",
       "zip"=>"95814"}],
    "party"=>"Nonpartisan",
    "phones"=>["(916) 319-0800"],
    "urls"=>["http://www.cde.ca.gov/"],
    "emails"=>["superintendent@cde.ca.gov"],
    "channels"=>
     [{"type"=>"Facebook", "id"=>"CAEducation"},
      {"type"=>"Twitter", "id"=>"cadepted"}]}]}

pp representatives_data["officials"]
